USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS PROJECT WITH WAREHOUSE_SIZE = 'x-small';

CREATE DATABASE IF NOT EXISTS PROJECT_DB;

CREATE ROLE IF NOT EXISTS PROJECT_ROLE;

SHOW GRANTS ON WAREHOUSE PROJECT ;

GRANT USAGE ON WAREHOUSE PROJECT TO PROJECT_ROLE ;

GRANT ALL ON DATABASE PROJECT_DB TO PROJECT_ROLE;

SHOW GRANTS ON DATABASE PROJECT_DB ;

GRANT ROLE PROJECT_ROLE TO USER jhonalevc;

USE ROLE PROJECT_ROLE;

CREATE SCHEMA IF NOT EXISTS PROJECT_DB.PROJECT_SCHEMA;
